# Generated by Django 4.2.2 on 2024-11-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IZONapp', '0003_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('DESKTOP', 'DESKTOP'), ('LAPTOPS', ' LAPTOPS'), ('PRINTERS', 'PRINTERS'), ('SCANNERS ', 'SCANNERS '), (' CCTV', ' CCTV'), ('ROLLS AND RIBBONS', 'ROLLS AND RIBBONS'), ('SECURITY SYSTEM', 'SECURITY SYSTEM'), ('ACCESSORIES', 'ACCESSORIES')], max_length=50),
        ),
    ]
