# Generated by Django 4.2.2 on 2024-11-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IZONapp', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Catimage',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
    ]
