# Generated by Django 4.2.2 on 2024-10-18 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IZONapp', '0004_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
