# Generated by Django 4.2.2 on 2024-11-18 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IZONapp', '0005_product_catimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('DESKTOP', 'DESKTOP'), ('LAPTOPS', 'LAPTOPS'), ('PRINTERS', 'PRINTERS'), ('SCANNERS', 'SCANNERS'), ('CCTV', 'CCTV'), ('ROLLS AND RIBBONS', 'ROLLS AND RIBBONS'), ('SECURITY SYSTEM', 'SECURITY SYSTEM'), ('ACCESSORIES', 'ACCESSORIES')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='Catimage',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='IZONapp.category'),
        ),
    ]
