# Generated by Django 4.2.2 on 2024-10-18 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IZONapp', '0005_remove_product_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categoryproduct',
        ),
    ]
