# Generated by Django 4.2.2 on 2024-10-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

  

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
