# Generated by Django 4.2.2 on 2024-11-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IZONapp', '0007_alter_product_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('DESKTOP', 'DESKTOP'), ('LAPTOPS', 'LAPTOPS'), ('PRINTERS', 'PRINTERS'), ('SCANNERS', 'SCANNERS'), ('CCTV', 'CCTV'), ('ROLLS AND RIBBONS', 'ROLLS AND RIBBONS'), ('SECURITY SYSTEM', 'SECURITY SYSTEM'), ('ACCESSORIES', 'ACCESSORIES')], max_length=50),
        ),
    ]
