# Generated by Django 4.2.2 on 2024-10-19 07:42

from django.db import migrations


class Migration(migrations.Migration):

   

    operations = [
        migrations.RemoveField(
            model_name='imageupload',
            name='title',
        ),
    ]
