# Generated by Django 4.2.2 on 2024-10-19 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IZONapp', '0009_remove_imageupload_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='title',
        ),
    ]
