# Generated by Django 4.2.2 on 2024-10-23 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IZONapp', '0014_rename_category_categoryproduct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Categoryproduct',
        ),
    ]
